config/routes.rb
Rails.application.routes.draw do


  root 'homepage#index'
  get 'recipes/new', to: 'recipes#new'
  # get 'recipes/:id', to: 'homepage#index'

  resources :measurement_units
  resources :ingredients
  resources :tags
  resources :recipes
  resources :recipe_tag_relationships
  resources :recipe_ingredient_relationships
  resources :recipe_steps
  resources :users

  scope :api, defaults: {format: :json} do
    scope :v1 do
      devise_for :users,  controllers: { sessions: :sessions },
                          path_names: { sign_in: :login }

      resource :user, only: [ :update]
      resources :measurement_units
      resources :ingredients, only: [ :create, :index, :show]
      resources :tags, only: [:create, :index, :show]
      resources :recipes


      get '/users/:id', to: 'users#show'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe_ingredient_relationship.rb
class RecipeIngredientRelationship < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
  belongs_to :measurement_unit
end

app/controllers/recipe_ingredient_relationships_controller.rb
class RecipeIngredientRelationshipsController < ApplicationController
  before_action :set_recipe_ingredient_relationship, only: [:show, :edit, :update, :destroy]

  # GET /recipe_ingredient_relationships
  # GET /recipe_ingredient_relationships.json
  def index
    @recipe_ingredient_relationships = RecipeIngredientRelationship.all
  end

  # GET /recipe_ingredient_relationships/1
  # GET /recipe_ingredient_relationships/1.json
  def show
  end

  # GET /recipe_ingredient_relationships/new
  def new
    @recipe_ingredient_relationship = RecipeIngredientRelationship.new
  end

  # GET /recipe_ingredient_relationships/1/edit
  def edit
  end

  # POST /recipe_ingredient_relationships
  # POST /recipe_ingredient_relationships.json
  def create
    @recipe_ingredient_relationship = RecipeIngredientRelationship.new(recipe_ingredient_relationship_params)

    respond_to do |format|
      if @recipe_ingredient_relationship.save
        format.html { redirect_to @recipe_ingredient_relationship.recipe, notice: 'Recipe ingredient relationship was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_ingredient_relationship }
      else
        format.html { render :new }
        format.json { render json: @recipe_ingredient_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_ingredient_relationships/1
  # PATCH/PUT /recipe_ingredient_relationships/1.json
  def update
    respond_to do |format|
      if @recipe_ingredient_relationship.update(recipe_ingredient_relationship_params)
        format.html { redirect_to @recipe_ingredient_relationship.recipe, notice: 'Recipe ingredient relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_ingredient_relationship }
      else
        format.html { render :edit }
        format.json { render json: @recipe_ingredient_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_ingredient_relationships/1
  # DELETE /recipe_ingredient_relationships/1.json
  def destroy
    @recipe_ingredient_relationship.destroy
    respond_to do |format|
      format.html { redirect_to recipe_ingredient_relationships_url, notice: 'Recipe ingredient relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_ingredient_relationship
      @recipe_ingredient_relationship = RecipeIngredientRelationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_ingredient_relationship_params
      params.require(:recipe_ingredient_relationship).permit!
    end
end

app/helpers/recipe_ingredient_relationships_helper.rb
module RecipeIngredientRelationshipsHelper
end

app/views/recipe_ingredient_relationships/_form.html.erb
<%= form_with(model: recipe_ingredient_relationship, local: true) do |form| %>
  <% if recipe_ingredient_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_ingredient_relationship.errors.count, "error") %> prohibited this recipe_ingredient_relationship from being saved:</h2>

      <ul>
      <% recipe_ingredient_relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= form.label "Recipe"%>
  <%= form.collection_select(:recipe_id, Recipe.all, :id, :name, { :prompt => 'Select recipe', :selected => recipe_ingredient_relationship.recipe_id }, { class: 'form-control' }) %>
   </div>
    <div class="field">
    <%= form.label "Ingredient"%>
  <%= form.collection_select(:ingredient_id, Ingredient.all, :id, :name, { :prompt => 'Select Ingredient', :selected => recipe_ingredient_relationship.ingredient_id }, { class: 'form-control' }) %>
  </div>
    <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>
  <div class="field">
  <%= form.label "Measurement Unit"%>
  <%= form.collection_select(:measurement_unit_id, MeasurementUnit.all, :id, :singular_name, { :prompt => 'Select measurement unit', :selected => recipe_ingredient_relationship.measurement_unit_id }, { class: 'form-control' }) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_ingredient_relationships/edit.html.erb
<h1>Editing Recipe Ingredient Relationship</h1>

<%= render 'form', recipe_ingredient_relationship: @recipe_ingredient_relationship %>

<%= link_to 'Show', @recipe_ingredient_relationship %> |
<%= link_to 'Back', recipe_ingredient_relationships_path %>

app/views/recipe_ingredient_relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Ingredient Relationships</h1>

<table>
  <thead>
    <tr>
      <th>Recipe ID</th>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Quantity</th>
      <th>MeasurementUnit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_ingredient_relationships.each do |recipe_ingredient_relationship| %>
      <tr>
        <td><%= recipe_ingredient_relationship.recipe.id %></td>
        <td><%= recipe_ingredient_relationship.recipe.name %></td>
        <td><%= recipe_ingredient_relationship.ingredient.name %></td>
        <td><%= recipe_ingredient_relationship.quantity %></td>
        <td><%= recipe_ingredient_relationship.measurement_unit.singular_name %></td>

        <td><%= link_to 'Show', recipe_ingredient_relationship %></td>
        <td><%= link_to 'Edit', edit_recipe_ingredient_relationship_path(recipe_ingredient_relationship) %></td>
        <td><%= link_to 'Destroy', recipe_ingredient_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe Ingredient Relationship', new_recipe_ingredient_relationship_path %>

app/views/recipe_ingredient_relationships/new.html.erb
<h1>New Recipe Ingredient Relationship</h1>

<%= render 'form', recipe_ingredient_relationship: @recipe_ingredient_relationship %>

<%= link_to 'Back', recipe_ingredient_relationships_path %>

app/views/recipe_ingredient_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_ingredient_relationship_path(@recipe_ingredient_relationship) %> |
<%= link_to 'Back', recipe_ingredient_relationships_path %>