config/routes.rb
Rails.application.routes.draw do


  root 'homepage#index'
  get 'recipes/new', to: 'recipes#new'
  # get 'recipes/:id', to: 'homepage#index'

  resources :measurement_units
  resources :ingredients
  resources :tags
  resources :recipes
  resources :recipe_tag_relationships
  resources :recipe_ingredient_relationships
  resources :recipe_steps
  resources :users

  scope :api, defaults: {format: :json} do
    scope :v1 do
      devise_for :users,  controllers: { sessions: :sessions },
                          path_names: { sign_in: :login }

      resource :user, only: [ :update]
      resources :measurement_units
      resources :ingredients, only: [ :create, :index, :show]
      resources :tags, only: [:create, :index, :show]
      resources :recipes


      get '/users/:id', to: 'users#show'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
  
end

app/controllers/recipe_steps_controller.rb
class RecipeStepsController < ApplicationController
  before_action :set_recipe_step, only: [:show, :edit, :update, :destroy]

  # GET /recipe_steps
  # GET /recipe_steps.json
  def index
    @recipe_steps = RecipeStep.all
  end

  # GET /recipe_steps/1
  # GET /recipe_steps/1.json
  def show
  end

  # GET /recipe_steps/new
  def new
    @recipe_step = RecipeStep.new
  end

  # GET /recipe_steps/1/edit
  def edit
  end

  # POST /recipe_steps
  # POST /recipe_steps.json
  def create
    @recipe_step = RecipeStep.new(recipe_step_params)

    respond_to do |format|
      if @recipe_step.save
        format.html { redirect_to @recipe_step, notice: 'Recipe step was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_step }
      else
        format.html { render :new }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_steps/1
  # PATCH/PUT /recipe_steps/1.json
  def update
    respond_to do |format|
      if @recipe_step.update(recipe_step_params)
        format.html { redirect_to @recipe_step, notice: 'Recipe step was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_step }
      else
        format.html { render :edit }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_steps/1
  # DELETE /recipe_steps/1.json
  def destroy
    @recipe_step.destroy
    respond_to do |format|
      format.html { redirect_to recipe_steps_url, notice: 'Recipe step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_step
      @recipe_step = RecipeStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_step_params
      params.require(:recipe_step).permit!
    end
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
end

app/views/recipe_steps/_form.html.erb
<%= form_with(model: recipe_step, local: true) do |form| %>
  <% if recipe_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_step.errors.count, "error") %> prohibited this recipe_step from being saved:</h2>

      <ul>
      <% recipe_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= form.label "Recipe"%>
    <%= form.collection_select(:recipe_id, Recipe.all, :id, :name, { :prompt => 'Select recipe', :selected => recipe_step.recipe_id }, { class: 'form-control' }) %>
   </div>

    <div class="field">
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>
      <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_steps/edit.html.erb
<h1>Editing Recipe Step</h1>

<%= render 'form', recipe_step: @recipe_step %>

<%= link_to 'Show', @recipe_step %> |
<%= link_to 'Back', recipe_steps_path %>

app/views/recipe_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Steps</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Order</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_steps.each do |recipe_step| %>
      <tr>
        <td><%= recipe_step.recipe.name %></td>
        <td><%= recipe_step.order %></td>
        <td><%= recipe_step.description %></td>
        <td><%= link_to 'Show', recipe_step %></td>
        <td><%= link_to 'Edit', edit_recipe_step_path(recipe_step) %></td>
        <td><%= link_to 'Destroy', recipe_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe Step', new_recipe_step_path %>

app/views/recipe_steps/new.html.erb
<h1>New Recipe Step</h1>

<%= render 'form', recipe_step: @recipe_step %>

<%= link_to 'Back', recipe_steps_path %>

app/views/recipe_steps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_step_path(@recipe_step) %> |
<%= link_to 'Back', recipe_steps_path %>