config/routes.rb
Rails.application.routes.draw do


  root 'homepage#index'
  get 'recipes/new', to: 'recipes#new'
  # get 'recipes/:id', to: 'homepage#index'

  resources :measurement_units
  resources :ingredients
  resources :tags
  resources :recipes
  resources :recipe_tag_relationships
  resources :recipe_ingredient_relationships
  resources :recipe_steps
  resources :users

  scope :api, defaults: {format: :json} do
    scope :v1 do
      devise_for :users,  controllers: { sessions: :sessions },
                          path_names: { sign_in: :login }

      resource :user, only: [ :update]
      resources :measurement_units
      resources :ingredients, only: [ :create, :index, :show]
      resources :tags, only: [:create, :index, :show]
      resources :recipes


      get '/users/:id', to: 'users#show'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_tag_relationships, dependent: :delete_all
  has_many :tags, through: :recipe_tag_relationships
  has_many :recipe_ingredient_relationships, dependent: :delete_all
  has_many :ingredients, through: :recipe_ingredient_relationships
  belongs_to :user, foreign_key: "author_id"
  has_many :recipe_steps, dependent: :delete_all
  accepts_nested_attributes_for :recipe_ingredient_relationships
  accepts_nested_attributes_for :recipe_tag_relationships




  def author_name
    return author.first_name + " "+ author.last_name
  end

  def author
    return User.find(author_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create]


  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe_tag_relationships = RecipeTagRelationship.where(recipe_id: @recipe.id)
    @recipe_ingredient_relationships = RecipeIngredientRelationship.where(recipe_id: @recipe.id)

  end

  # POST /recipes
  # POST /recipes.json
  def create

    additional_params = {
      author_id: current_user.id
    }
    @recipe = Recipe.new(author_id: current_user.id, name: recipe_params[:name], description: recipe_params[:description], banner_image_url: recipe_params[:banner_image_url])

    @ingredients = []
    @steps = []
    @tags = []
    # TODO create the recipe ingredient relationships
    recipe_params[:ingredients].each do |ingredient|
      @ingredients.push(RecipeIngredientRelationship.new(recipe: @recipe, ingredient_id: ingredient[:ingredient_id], quantity: ingredient[:quantity], measurement_unit_id: ingredient[:measurement_unit_id]))
    end unless recipe_params[:ingredients] == nil

    # TODO create the recipe steps
    recipe_params[:steps].each do |step|
      @steps.push(RecipeStep.new(recipe: @recipe, description: step[:description], order: step[:order], created_at: Time.now, updated_at: Time.now))
    end unless recipe_params[:steps] == nil

    recipe_params[:tags].each do |t|
      @tags.push(RecipeTagRelationship.new(tag_id: t))
    end unless recipe_params[:tags] == nil

    # binding.pry
    #Attempt the transaction. If it succeeds, render success message, otherwise render failure message.
    begin
      ActiveRecord::Base.transaction do
        @recipe.save!
        @ingredients.each do |ingredient|
          ingredient.recipe_id = @recipe.id
          ingredient.save!
        end
        @steps.each do |step|
          step.recipe_id = @recipe.id
          step.save!
        end

        @tags.each do |tag|
          tag.recipe_id = @recipe.id
          tag.save!
        end
      end
      respond_to do |format|
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      end
    rescue
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end

    # respond_to do |format|
    #   if @recipe.save
    #     format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
    #     format.json { render :show, status: :created, location: @recipe }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @recipe.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      # params.require(:recipe).permit(:name, :description, :banner_image_url, :ingredients => [:ingredient_id, :quantity, :measurement_unit_id], :steps => [:order, :description])
      params.require(:recipe).permit!
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_field :banner_image_url %>
  </div>


  <div class="actions"> 
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>
<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>
<br/>
<br/>
<%= render 'form', recipe: @recipe %>
<br/>

<h2>Tags</h2>
<%= link_to 'Add Tag', new_recipe_tag_relationship_path %>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_tag_relationships.each do |recipe_tag_relationship| %>

      <tr>
            <td><%= recipe_tag_relationship.tag.name %></td>
      <td><%= recipe_tag_relationship.recipe.name %></td>
        <td><%= link_to 'Show', recipe_tag_relationship %></td>
        <td><%= link_to 'Edit', edit_recipe_tag_relationship_path(recipe_tag_relationship) %></td>
        <td><%= link_to 'Destroy', recipe_tag_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<br/>
<h2>Ingredients</h2>
<%= link_to 'Add Ingredient', new_recipe_ingredient_relationship_path %>
<table>
  <thead>
    <tr>
      <th>Recipe ID</th>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Quantity</th>
      <th>MeasurementUnit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_ingredient_relationships.each do |recipe_ingredient_relationship| %>
      <tr>
        <td><%= recipe_ingredient_relationship.recipe.id %></td>
        <td><%= recipe_ingredient_relationship.recipe.name %></td>
        <td><%= recipe_ingredient_relationship.ingredient.name %></td>
        <td><%= recipe_ingredient_relationship.quantity %></td>
        <td><%= recipe_ingredient_relationship.measurement_unit.singular_name %></td>

        <td><%= link_to 'Show', recipe_ingredient_relationship %></td>
        <td><%= link_to 'Edit', edit_recipe_ingredient_relationship_path(recipe_ingredient_relationship) %></td>
        <td><%= link_to 'Destroy', recipe_ingredient_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>


<br/>
<br/>
<h2>Recipe Steps</h2>
<%= link_to 'Add another step', new_recipe_step_path %>
<table>
  <tr>
    <th>Order</th>
    <th>Description</th>
  </tr>
  <% @recipe.recipe_steps.each do |recipe_step| %>
    <%= form_with(model: recipe_step, local: true) do |form| %>
      <% if recipe_step.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(recipe_step.errors.count, "error") %> prohibited this recipe_step from being saved:</h2>

          <ul>
          <% recipe_step.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <tr>
          <td>
            <%= recipe_step.order %>
          </td>
          <td>
            <div class="field">
              <%= form.label :description %>
              <%= form.text_field :description %>
            </div>
          </td>
          <td>
            <div class="actions">
              <%= form.submit %>
            </div>
          </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>banner_image_url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.banner_image_url %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
First, create the recipe. Then after that you can add ingredients, steps, and tags to the recipe.
<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h3 style="margin-left:16px">
<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' } %>

</h3>